//
// Created by UtoKing on 2022/10/19.
//

#ifndef PROJECT_2_MATRIX_OPERATION_MATRIXOPERATION_H
#define PROJECT_2_MATRIX_OPERATION_MATRIXOPERATION_H

#endif //PROJECT_2_MATRIX_OPERATION_MATRIXOPERATION_H

#include "matrix.h"
#include "malloc.h"
